spring.application.name=auth-service

server.port=4005


# Local postgres setting for "pms-auth-service" DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/pms-auth-db
spring.datasource.username=postgres
spring.datasource.password=0000

# Hibernate and JPA
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# JWT
jwt.secret=n7cy5htofe1GtBOgXDcFbzd0Hltf0th4h0Fat4guziX