spring.application.name=auth-service
server.port=4005

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Default profile
spring.profiles.default=local

# JWT secret (same everywhere)
jwt.secret=CZksJX44bNxwS+xclTplk7S3wMFk3g7YkuXJW2e4aeo=
