patient:
  service:
    url: http://patient-service:4000

auth:
  service:
    url: http://auth-service:4005

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${auth.service.url}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service
          uri: ${patient.service.url}
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1

        - id: api-docs
          uri: ${patient.service.url}
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs