server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
          ## REST CLIENT --> http://localhost:4000/api/patients
          ## API GATEWAY --> http://patient-service:4000/patients
          ## PATIENT SERVICE (Spring Boot App) -->/patients -->Patients Array
        - id: patient-service-route
          uri: http://patient-service:4000
          predicate:
            - path=/api/patients/**
          filter:
            - strip-prefix=1

          ## REST-CLIENT --> http://loclahost:4000/api-docs/patients
          ## API-GATEWAY --> http://patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicate:
            - path=/api-docs/patients
          filters:
            - rewrite-path=/api-docs/patient,/v3/api-docs