patient:
  service:
    url: http://patient-service:4000

auth:
  service:
    url: http://auth-service:4005

spring:
  cloud:
    gateway:
      routes:
        # Route for /auth/** to auth-service
        - id: auth-service
          uri: ${auth.service.url}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route for /api/patients/** to patient-service
        - id: patient-service
          uri: ${patient.service.url}
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/patients to patient-service /v3/api-docs
        - id: api-docs
          uri: ${patient.service.url}
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs