patient:
  service:
    url: http://localhost:4000

auth:
  service:
    url: http://localhost:4005

analytics:
  service:
    url: http://localhost:4006

spring:
  cloud:
    gateway:

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: ${auth.service.url}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service
          uri: ${patient.service.url}
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: websocket-route
          uri: ${analytics.service.url}
          predicates:
            - Path=/ws/**

        - id: api-docs
          uri: ${patient.service.url}
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs