### Post Request to add new patients.
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Chimapnzee aka AZAD",
  "email": "Azad@gandu.com",
  "address": "Gandu Nagar",
  "dateOfBirth": "1947-08-15",
  "registeredDate": "2026-04-03"
}