services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: rohit
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pms
    ports:
      - "5432:5432"