### Post Request to add new patients.
POST http://localhost:4000/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test Name",
  "email": "Test@email.com",
  "address": "No Address",
  "dateOfBirth": "1947-08-15",
  "registeredDate": "2026-10-03"
}