#Docker - postgres setting for Patient DB
spring.datasource.url=jdbc:postgresql://postgres:5432/pms-patient-db
spring.datasource.username=rohit
spring.datasource.password=1234

spring.kafka.bootstrap-servers=kafka:9092


