spring.application.name=patient-service

#Docker postgres setting
spring.datasource.url=jdbc:postgresql://postgres:5432/pms
spring.datasource.username=rohit
spring.datasource.password=1234

# Local postgres setting
#spring.datasource.url=jdbc:postgresql://localhost:5432/pms
#spring.datasource.username=postgres
#spring.datasource.password=0000

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Disbale while running the docker
#BILLING_SERVICE_ADDRESS=billing-service
#BILLING_SERVICE_GRPC_PORT=9001

server.port=4000

logging.level.root=info