spring.application.name=patient-service

spring.datasource.url=jdbc:postgresql://postgres:5432/pms
spring.datasource.username=rohit
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=4000

logging.level.root=info