# Local postgres setting for Patient DB
spring.datasource.url=jdbc:postgresql://localhost:5432/pms-patient-db
spring.datasource.username=postgres
spring.datasource.password=0000

# Billing service only needed in Local
BILLING_SERVICE_ADDRESS=billing-service
BILLING_SERVICE_GRPC_PORT=9001

spring.kafka.bootstrap-servers=localhost:9092
